os: Visual Studio 2019
version: 3.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

install:
  - ps: npm install --global bower --loglevel=error
  - ps: npm install --global npm

build_script:
  - ps: .\Build.ps1

skip_tags: false
test: off
